Repository Uniq-dev/hacktober2021, pull requests merged in 2021-10, with the labels that each got.

#2 Updated palindrome.py
  palindrome.py
Labels: hacktoberfest-accepted

#3 Update MotionDetector.py
  MotionDetector.py
Labels: hacktoberfest-accepted

#6 Update calc.py
  calc.py
Labels: hacktoberfest-accepted

#13 Create BinarySearch.py
  BinarySearch.py
Labels: Hacktoberfest, hacktoberfest-accepted

#12 Created driver code for access through CLI instead of altering main code
  palindrome.py
Labels: Hacktoberfest, hacktoberfest-accepted

#15 Added bubble sort
  Bubble Sort.py
Labels: hacktober, Hacktoberfest, hacktoberfest-accepted

#19 Added Shell Sort program using Python
  shellsort.py
Labels: Hacktoberfest, hacktoberfest-accepted

#23 Added a program to check if a number is armstrong
  Armstrong.py
  WebApp_ListOfItems/app.py
  WebApp_ListOfItems/static/css/main.css
  WebApp_ListOfItems/templates/base.html
  WebApp_ListOfItems/templates/index.html
Labels: hacktober, Hacktoberfest, hacktoberfest-accepted

#31 readme displays contibutors
  README.md
Labels: hacktober, Hacktoberfest, hacktoberfest-accepted

#33 Guess_Number.py
  Guess_Number.py
Labels: good first issue, hacktober, Hacktoberfest, hacktoberfest-accepted

#42 feat: Added Simple Portfolio Webpage (#17)
  Portfolio_Webpage/CSS/styles.css
  Portfolio_Webpage/Images/cloud.png
  Portfolio_Webpage/Images/mountain.png
  Portfolio_Webpage/Images/projects.png
  Portfolio_Webpage/Images/skills.png
  Portfolio_Webpage/Images/web-dev.png
  Portfolio_Webpage/favicon.ico
  Portfolio_Webpage/index.html
Labels: hacktober, Hacktoberfest, hacktoberfest-accepted

#40 Added Circular linked list
  Circular_Linked_List.py
Labels: hacktober

#41 program to solve sudoku
  sudoku.py
Labels: hacktober

#53 Create todolist.py
  Python/todolist.py
Labels: hacktober, Hacktoberfest, hacktoberfest-accepted

#56 Merge sort using python
  Python/mergesort.py
Labels: hacktober, Hacktoberfest, hacktoberfest-accepted

#58 Issue #50 Resolved
  C++/0-1Knapsack.cpp
Labels: hacktober, Hacktoberfest, hacktoberfest-accepted

#64 Create Fibonacci.py
  Python/Fibonacii.py
Labels: hacktober, Hacktoberfest, hacktoberfest-accepted
